version: '3.2'

services:
   snmp-server:
        build:
            context: .
            dockerfile: Dockerfile  
        container_name: snmp-server
        ports:
            - "1161:1161/udp"
        restart: unless-stopped