version: '3.2'

services:
    snmp-sever:
        image : snmp-server
        container_name: snmp-server
        ports:
            - "1161:1161/udp"
        
        restart: unless-stopped

        